name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup nodejs
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Build front-end
        run: |
          cd client
          yarn install
          yarn build

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build

      - name: Run unit tests
        run: npm run test

      - name: Build container
        run: docker build -t my-app.

      - name: Deploy to staging
        run: terraform apply -var-file=staging.tfvars

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to production
        run: terraform apply -var-file=production.tfvars
